services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql_shared
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Solo contraseña root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Para acceso desde host u otros contenedores
    networks:
      shared:  # ✅ Red explícita
        aliases:
          - mysql 
    

  adminer:  # 🆕 Servicio Adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql  # ✨ Se conecta automáticamente al servicio MySQL
    networks:
      - shared
    depends_on:
      - mysql

networks:
  shared:
    external: true

volumes:
  mysql_data:
    driver: local